<?php

/**
 * BaseServerGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $enabled
 * @property Doctrine_Collection $Servers
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method boolean             getEnabled() Returns the current record's "enabled" value
 * @method Doctrine_Collection getServers() Returns the current record's "Servers" collection
 * @method ServerGroup         setName()    Sets the current record's "name" value
 * @method ServerGroup         setEnabled() Sets the current record's "enabled" value
 * @method ServerGroup         setServers() Sets the current record's "Servers" collection
 * 
 * @package    monistix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServerGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('server_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Server as Servers', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}