<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/15 14:53:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=monistix',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
